# Generated by Django 5.2rc1 on 2025-04-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ac_output_voltage', models.FloatField()),
                ('dc_battery_voltage', models.FloatField()),
                ('dc_battery_current', models.FloatField()),
                ('load_power', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('predicted_load', models.FloatField(blank=True, null=True)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('backup_triggered', models.BooleanField(default=False)),
            ],
        ),
    ]
