# Generated by Django 5.2rc1 on 2025-04-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('backup_file', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('size_kb', models.FloatField(default=0)),
                ('trigger_reason', models.CharField(max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('triggered_by', models.ManyToManyField(blank=True, related_name='backups', to='monitoring.energylog')),
            ],
        ),
    ]
