# Generated by Django 5.2rc1 on 2025-04-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_backuplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='trigger_reason',
            field=models.CharField(choices=[('ANOMALY', 'Anomaly Detection'), ('PREDICTION', 'Load Prediction'), ('MANUAL', 'Manual Backup'), ('SCHEDULED', 'Scheduled Backup'), ('UNKNOWN', 'Unknown Reason')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['-timestamp'], name='monitoring__timesta_168d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='energylog',
            index=models.Index(fields=['-timestamp'], name='monitoring__timesta_f14172_idx'),
        ),
    ]
