# Generated by Django 5.2 on 2025-04-30 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_systemsettings_maintenance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='maintenance_time',
            field=models.TimeField(default=datetime.time(0, 0, 0, 314035), help_text='Час виконання щоденного обслуговування (очищення даних)'),
        ),
    ]
