# Generated by Django 5.2 on 2025-05-11 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_update_energy_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'Налаштування планувальника', 'verbose_name_plural': 'Налаштування планувальника'},
        ),
        migrations.AlterField(
            model_name='energylog',
            name='dc_battery_current',
            field=models.FloatField(verbose_name='Струм акамулятора (А)'),
        ),
        migrations.AlterField(
            model_name='energylog',
            name='dc_battery_voltage',
            field=models.FloatField(verbose_name='Напруга акамулятора (В)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='maintenance_time',
            field=models.TimeField(default=datetime.time(0, 0, 0, 314519), help_text='Розклад роботи з підтримки бази даних'),
        ),
    ]
